"""duda

Revision ID: 6ec53e96cb4a
Revises: 
Create Date: 2024-09-13 17:37:32.060797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec53e96cb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id_eventos', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('local', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_eventos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
